owner: epaynter
repo: tendral-status

sites:
  - name: Tendral Health
    url: https://www.tendralhealth.com/api/ping
    expectedStatusCodes:
      - 200
    headers:
      - "User-Agent: Mozilla/5.0 (compatible; Upptime/1.0; +https://github.com/epaynter/tendral-status)"
